spring.application.name=skillswap
server.port=8080

spring.datasource.url=jdbc:h2:mem:skillswapdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

skillswap.jwt.secret=skillswap-dev-secret-change-me
skillswap.jwt.expiration-seconds=86400

springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.path=/api/v1/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
